- title: Automations
  path: automations
  icon: mdi:alpha-a-box
  cards:
    - type: vertical-stack
      cards:
        - !include
          - '../templates/system_header.yaml'
          - name: Create your own view here
            icon: mdi:alpha-a-box
            content: Automations