title: Security
path: security
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: quick-access-menu
        variables:
          - name1: Alarm
          - icon1: shield-home
          - path1: alarm
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '## Security'
      - type: custom:decluttering-card
        template: header
        variables:
          - content: "##### Camera's"
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.gallerij_camera
            title: Camera's  
            aspect_ratio: 16x9
            deep_press: true
          - !include ../includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.woonkamer_camera
            title: Camera's
            aspect_ratio: 16x9
            deep_press: true
          - !include ../includes/blank-card.yaml

### The following piece is for tablets only, You can leave this out if not needed.
  - type: custom:state-switch
    entity: user
    states:
      Home Assistant:
        type: vertical-stack
        cards:
          - type: markdown 
            style: |
              ha-card {
                background: none;
                color: white;
                box-shadow: none;
                text-align: end;
                font-size: 45px;
                height: 155px;
              }
            content: '# [[ sensor.time.state ]]'
### End of tablet code.

  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Doors'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.voordeur
              - name: Voordeur
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.woonkamer_deur
              - name: Woonkamer
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.slaapkamer_deur
              - name: Slaapkamer
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - !include ../includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Motion'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.dafang_motion_sensor
              - name: Gallerij
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.motion_bijkeuken
              - name: Bijkeuken
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.motion_toilet
              - name: Toilet
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - !include ../includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header
        variables:
          - content: '##### Alarms'
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button
            variables:
              - entity: binary_sensor.fire_30
              - name: Rookmelder
              - icon: smoke-detector
              - show_last_changed: true
              - tap_action: more-info
          - type: 'custom:button-card'
            color_type: blank-card
            aspect_ratio: 1/1
          - type: 'custom:button-card'
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../includes/blank-card.yaml
      - !include ../includes/bottom-card.yaml