# lovelace_gen

- title: Security
  path: security
  icon: mdi:alert
  cards:
    - type: vertical-stack
      cards:
        - type: custom:state-switch
          entity: input_boolean.header_advanced_mode_security          
          states:
            "off":
              !include
              - '../templates/system_header.yaml'
              - name: input_text.name_header_secondary_security
                system_header: input_boolean.header_secondary_security
                icon: "[[[ return `${states['input_text.icon_header_security'].state}` ]]]"
                {% raw %}
                content: "{{ states.input_text.name_header_security.state }}"
                {% endraw %}
            "on":
              !include
              - '../templates/system_header_advanced.yaml'
              - name: "{{ _global.header_secondary.security|default('return `Set your own template in YAML`') }}"
                system_header: input_boolean.header_secondary_security
                icon: "[[[ return `${states['input_text.icon_header_security'].state}` ]]]"
{% raw %}
                content: "{{ states.input_text.name_header_security.state }}"
        - type: conditional
          conditions:
            - entity: input_boolean.edit_mode
              state: "on"
          card:
            !include
            - '../templates/edit_mode_warning.yaml'
            - template: security_layout_popup.yaml
        - type: conditional
          conditions:
            - entity: input_boolean.security_cameras
              state: "on"
          card:
            !include
            - '../templates/auto_fill_camera_template.yaml'
            - content: "{{ states.input_text.name_cameras.state }}"
              group: group.all_cameras
        - type: conditional
          conditions:
            - entity: input_boolean.security_doors
              state: "on"
          card:
            !include
            - '../templates/auto_fill_security_template.yaml'
            - content: "{{ states.input_text.name_doors.state }}"
              group: group.all_door_sensors
        - type: conditional
          conditions:
            - entity: input_boolean.security_windows
              state: "on"
          card:
            !include
            - '../templates/auto_fill_security_template.yaml'
            - content: "{{ states.input_text.name_windows.state }}"
              group: group.all_window_sensors
        - type: conditional
          conditions:
            - entity: input_boolean.security_motion
              state: "on"
          card:
            !include
            - '../templates/auto_fill_security_template.yaml'
            - content: "{{ states.input_text.name_motion.state }}"
              group: group.all_motion_sensors
        - type: conditional
          conditions:
            - entity: input_boolean.security_other
              state: "on"
          card:
            !include
            - '../templates/auto_fill_security_template.yaml'
            - content: "{{ states.input_text.name_other.state }}"
              group: group.all_smoke_detectors
        - type: conditional
          conditions:
            - entity: input_boolean.user_content_message
              state: "on"
          card:
            type: horizontal-stack
            cards:
              - !include ../includes/blank-card.yaml   
              - type: custom:layout-card
                cards:
                  - !include ../includes/edit_mode/message-user-content-edit-mode.yaml
              - !include ../includes/blank-card.yaml                     
        - type: conditional
          conditions:
            - entity: input_boolean.security_user_content
              state: "on"
          card:
            type: horizontal-stack
            cards:
              - !include ../includes/blank-card.yaml   
              - type: custom:layout-card
                cards:
                  !include ../../user_content/views/security_user_content.yaml
              - !include ../includes/blank-card.yaml   
{% endraw %}