- title: HKI Settings
  path: hki_settings_general
  cards:    
    - type: vertical-stack
      cards:
        - !include
          - '../../templates/system_header_advanced.yaml'
          - name: General
            icon: mdi:tools
            content: "HKI {{ states.input_text.name_header_settings.state }}"
            system_header: input_boolean.config_header
        - type: conditional
          conditions:
            - entity: input_boolean.edit_mode
              state: "on"
          card:
            !include
            - '../../templates/edit_mode_warning.yaml'
            - template: nothing_to_edit.yaml
        - !include
          - '../../templates/settings_back_button.yaml'
          - background_color: LightSeaGreen
        - type: custom:search-card
          style: |
            ha-card {
              border-radius: none;
              box-shadow: none;
              --paper-card-background-color: rgba(0,0,0,0.0);
              --primary-text-color: var(--category-text) !important;
              color: var(--category-text) !important;
              --text-primary-color: var(--category-text) !important;
              --secondary-text-color: var(--category-text) !important;
              --disabled-text-color: var(--category-text) !important;
            }
          max_results: 10
        - type: horizontal-stack
          cards:
            - !include ../../includes/blank-card.yaml
            - type: custom:layout-card
              cards:
                - type: conditional
                  conditions:
                    - entity: input_boolean.system_help
                      state: "on"
                  card:
                    type: markdown
                    style: |
                      ha-card {
                        background: rgba(0, 0, 0, 0.5);
                        border-radius: {{ states('input_select.border_radius') }};
                        box-shadow: {{ states('input_select.box_shadow') }};
                        font-size: 13px;
                        font-family: Helvetica;
                        color: white;
                      }                    
                    content: >
                      **Language and Icons:** Set up your language and icons here, you need a subscription for Fontawesome Pro. Warning: Selecting a language will erase all customization made in the advanced section.
                - type: entities
                  title: Language and Icons
                  show_header_toggle: false                          
                  style: |
                    ha-card {
                      border-radius: {{ states('input_select.border_radius') }};
                      box-shadow: {{ states('input_select.box_shadow') }};
                    }                        
                  entities: 
                    - entity: input_select.language_selector
                      name: Language
                    - entity: input_select.icon_selector
                      name: Icons
                - type: conditional
                  conditions:
                    - entity: input_boolean.system_help
                      state: "on"
                  card:
                    type: markdown
                    style: |
                      ha-card {
                        background: rgba(0, 0, 0, 0.5);
                        border-radius: {{ states('input_select.border_radius') }};
                        box-shadow: {{ states('input_select.box_shadow') }};
                        font-size: 13px;
                        font-family: Helvetica;
                        color: white;
                      }                    
                    content: >
                      **Edit Mode:** Edit mode lets you turn on/off elements of HKI on each view, you can also turn 'on' edit mode by tap and holding the upper right corner of the UI. Tap on the red bar on the respective view to use edit mode.
                - type: entities
                  title: Edit Mode
                  show_header_toggle: false                          
                  style: |
                    ha-card {
                      border-radius: {{ states('input_select.border_radius') }};
                      box-shadow: {{ states('input_select.box_shadow') }};
                    }                        
                  entities: 
                    - entity: input_boolean.edit_mode
                      name: Edit Mode
                - type: conditional
                  conditions:
                    - entity: input_boolean.system_help
                      state: "on"
                  card:
                    type: markdown
                    style: |
                      ha-card {
                        background: rgba(0, 0, 0, 0.5);
                        border-radius: {{ states('input_select.border_radius') }};
                        box-shadow: {{ states('input_select.box_shadow') }};
                        font-size: 13px;
                        font-family: Helvetica;
                        color: white;
                      }                    
                    content: >
                      **Messages:** Turn on/off the tutorial in HKI.
                - type: entities
                  title: System Messages
                  show_header_toggle: false                          
                  style: |
                    ha-card {
                      border-radius: {{ states('input_select.border_radius') }};
                      box-shadow: {{ states('input_select.box_shadow') }};
                    }                        
                  entities: 
                    - entity: input_boolean.user_content_message
                      name: User Content/Edit Mode message
                    - entity: input_boolean.system_help
                      name: HKI Settings help messages
            - !include ../../includes/blank-card.yaml