- title: HKI Settings
  path: hki_settings_alarm
  cards:    
    - type: vertical-stack
      cards:
        - !include
          - '../../templates/system_header_advanced.yaml'
          - name: Alarm
            icon: mdi:shield-home
            content: "HKI {{ states.input_text.name_header_settings.state }}"
            system_header: input_boolean.config_header
        - type: conditional
          conditions:
            - entity: input_boolean.edit_mode
              state: "on"
          card:
            !include
            - '../../templates/edit_mode_warning.yaml'
            - template: nothing_to_edit.yaml
        - !include
          - '../../templates/settings_back_button.yaml'
          - background_color: LightSeaGreen
        - type: custom:layout-card
          cards:
            - type: vertical-stack
              cards:
                - type: custom:layout-card
                  cards:
                    - type: conditional
                      conditions:
                        - entity: input_boolean.system_help
                          state: "on"
                      card:
                        type: markdown
                        style: |
                          ha-card {
                            background: rgba(0, 0, 0, 0.5);
                            border-radius: {{ states('input_select.border_radius') }};
                            box-shadow: {{ states('input_select.box_shadow') }};
                            font-size: 13px;
                            font-family: Helvetica;
                            color: white;
                          }                    
                        content: >
                          **Alarm:** Set up your alarm here, it must be an alarm_control_panel entity type! This will enable the alarm keypad and the lock icon/color on the frontpage. You can leave this field empty if you don't have or want to use an alarm. If you don't have one you can simply create one, refer to the HA docs on how to do that.
                    - type: entities
                      title: Alarm
                      show_header_toggle: false                          
                      style: |
                        ha-card {
                          border-radius: {{ states('input_select.border_radius') }};
                          box-shadow: {{ states('input_select.box_shadow') }};
                        }                        
                      entities: 
                        - entity: input_text.alarm_entity
                          type: 'custom:text-input-row'
