theme: jekyll-theme-slate
show_downloads: true
title: Homekit Infused 5
google_analytics: UA-158593402-1
buttons:
  zip_url: https://github.com/jimz011/homekit-infused/archive/refs/tags/2022.3.0.zip
  zip_title: Download latest release
  zip_hide: false
  tar_hide: true
