# Use this file to have the auto-fill card know which rooms you want to show on the lights and devices view.
# You only have 2 options, show room on the light view and show room on the devices view. Put it under the floor you want.
# If you have a basement, use floor 0 as the basement floor!

# The names used here MUST be exactly the same as what you've put in customize.yaml
# E.g.
#
# light.living_room:
#   friendly_name: Living Room Light
#   room: woonkamer
#
# The room names MUST be a list (see example below) and MUST be lowercase!

# Which rooms to show on lights view?
lights_rooms_floor_0:
  - berging
lights_rooms_floor_1:
  - woonkamer
  - slaapkamer
  - kleine_kamer
  - keuken
  - bijkeuken
  - gang
  - balkon
  - badkamer
  - toilet
lights_rooms_floor_2:
lights_rooms_floor_3:
lights_rooms_floor_4:

# Which rooms to show on devices view?
devices_rooms_floor_0:
devices_rooms_floor_1:
  - woonkamer
  - slaapkamer
  - kleine_kamer
  - keuken
  - bijkeuken
devices_rooms_floor_2:
devices_rooms_floor_3:
devices_rooms_floor_4: