automation:     
# Theme Selector
  - alias: 'themes'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_select.theme_selector_dark
      - platform: state
        entity_id: input_select.theme_selector_light
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
    action:
      - service: frontend.set_theme
        data_template:
          name: >
            {% if is_state('sun.sun', 'below_horizon') %}
              {{ states('input_select.theme_selector_dark') }}
            {% else %}
              {{ states('input_select.theme_selector_light') }}
            {% endif %}
          mode: >
            {% if is_state('sun.sun', 'below_horizon') %}
              dark
            {% else %}
              light
            {% endif %}
  - alias: 'theme editor'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sun.sun
      - platform: homeassistant
        event: start
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.settings_light_dark
          option: >
            {% if is_state('sun.sun', 'below_horizon') %}
              Dark
            {% else %}
              Light
            {% endif %}
  - alias: 'first time startup defaults'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.turn_on
        target:
          entity_id: script.hki_light_default
      - service: script.turn_on
        target:
          entity_id: script.hki_dark_default
      - service: script.turn_on
        target:
          entity_id: script.hki_header_greeting_default
      - service: automation.turn_off
        target:
          entity_id: automation.first_time_startup_defaults
        