- type: custom:mod-card
  style: |
    ha-card {
      margin-left: 7px;
      margin-right: 7px;
    }
  card:
    type: vertical-stack
    cards:
      - !include
        - '../../../hki-base/templates/other/title-text.yaml'
        - name: '&nbsp; Automations'
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - !include
                - '../../../hki-base/templates/button/button.yaml'
                - entity: group.film_kijken_automation
                  name: Dim Light
                  icon: mdi:movie
                  label: Movie
              - !include
                - '../../../hki-base/templates/button/button.yaml'
                - entity: group.deur_notifications
                  name: Door
                  icon: mdi:door
                  label: Notifications 
              - !include
                - '../../../hki-base/templates/button/button.yaml'
                - entity: group.vaatwasser_starten
                  name: Dishwasher On
                  icon: mdi:dishwasher
                  label: After Laundry 
          - type: horizontal-stack
            cards:
              - !include
                - '../../../hki-base/templates/button/button.yaml'
                - entity: automation.motion_detected_no_one_home_gallerij
                  name: Movement
                  icon: mdi:motion-sensor
                  label: Notification 
              - !include
                - '../../../hki-base/templates/button/button.yaml'
                - entity: group.all_automations
                  name: Automations
                  icon: mdi:alpha-a-box
                  label: All 
              - !include ../../../hki-base/includes/empty-button.yaml